### ISSUE TITLE
JavaScript Client and Server SDK documentation outdated

### ISSUE THREAD

**Issue by spethso** [dapr/docs#3308]
**Describe the issue**
The `DaprClient` and `DaprServer` classes in the `@dapr/dapr` package seem to have changed, which is not reflected in the docs. In both pages, the `DaprClient` and `DaprServer` are instantiated with multiple arguments (host, port, etc.). However, the current implementation requires a `Partial<DaprClientOptions>` or `Partial<DaprServerOptions>` instead of multiple arguments. For the `DaprServer` in the documentation, besides a `serverHost` and `serverPort`, a `daprHost` and a `daprPort` are provided. The `DaprServerOptions` class does not seem to have attributes for the additional arguments.

**URL of the docs**
https://docs.dapr.io/developing-applications/sdks/js/js-server/ and https://docs.dapr.io/developing-applications/sdks/js/js-client/

**Expected content**
The expected content would be an updated version of the documentation to fit the latest SDK version. 

**Screenshots**
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/23580428/229210393-cbfaadd9-b477-460b-b866-9c0995a6d614.png">
<img width="810" alt="image" src="https://user-images.githubusercontent.com/23580428/229210601-05fe37da-6406-4e9b-8c11-3b2d1e8ac930.png">
<img width="855" alt="image" src="https://user-images.githubusercontent.com/23580428/229210732-02a5fdd0-1c14-4eb7-b8ee-2a8451d07d88.png">
<img width="571" alt="image" src="https://user-images.githubusercontent.com/23580428/229210769-25b92945-6402-4481-924d-c1ab0a889c08.png">
<img width="580" alt="image" src="https://user-images.githubusercontent.com/23580428/229210910-5b8cf1b2-7f90-4208-a36b-0d912c29570a.png">
<img width="709" alt="image" src="https://user-images.githubusercontent.com/23580428/229210970-e22bf903-1de8-415c-8202-a7992ea3c6c8.png">

**Comment by hhunter-ms** [comment]
@shubham1172 let me know if you or someone else can help with this

**Comment by shubham1172** [comment]
Thanks @hhunter-ms for tagging.

Hi @spethso, did you get a chance to check the latest docs? https://v1-11.docs.dapr.io/developing-applications/sdks/js/js-client/

The documentation should be fixed there. Please let me know if something is missing.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/22132944/229859360-fb7099ff-756b-49a3-b728-f53ec8436489.png">

**Comment by spethso** [comment]
Hello @shubham1172, I have overseen the preview docs. My apologies. The documentation seems to be fixed there. However, I still have problems verifying that the code works as dapr always throws an error on the server side that it cannot start the sidecar. Hence, I am unsure whether something is missing in the docs or whether the error is on my side. Perhaps, we could look into it in more detail if you have a free minute? :)

**Comment by shubham1172** [comment]
@spethso that is strange, can you please share the error message with a minimal reproducible example?

**Comment by spethso** [comment]
Of course, I just created a repository with the relevant source code. You can find it under: https://github.com/spethso/dapr-nestjs-test

The error when executing "test-service-2" (the dapr service subscribing to the pubsub queue) looks like the following:
```
== APP == /Users/sandrospeth/Documents/Git Repositories/Mitrex/dapr-nest-demo/test-service-2/node_modules/@dapr/dapr/implementation/Client/DaprClient.js:148
== APP ==                     throw new Error("DAPR_SIDECAR_COULD_NOT_BE_STARTED");
== APP ==                           ^
== APP == Error: DAPR_SIDECAR_COULD_NOT_BE_STARTED
== APP ==     at Function.<anonymous> (/Users/sandrospeth/Documents/Git Repositories/Mitrex/dapr-nest-demo/test-service-2/node_modules/@dapr/dapr/implementation/Client/DaprClient.js:148:27)
== APP ==     at Generator.next (<anonymous>)
== APP ==     at fulfilled (/Users/sandrospeth/Documents/Git Repositories/Mitrex/dapr-nest-demo/test-service-2/node_modules/@dapr/dapr/implementation/Client/DaprClient.js:36:58)
== APP ==     at processTicksAndRejections (node:internal/process/task_queues:95:5)
❌  The App process exited with error code: exit status 1
ℹ️
terminated signal received: shutting down
✅  Exited Dapr successfully
❌  Error exiting App: exit status 1
```

Thanks for your help!

**Comment by shubham1172** [comment]
@spethso I cloned the repository and ran "test-service-2".

```bash
dapr run --app-id test-service-2 --dapr-http-port 3500 --app-protocol http --app-port 50051 -- npm start
```

In a separate terminal
```bash
dapr publish --publish-app-id test-service-2 --pubsub pubsub --topic topic-a --data 'test123'
✅  Event published successfully
```

App log -
```log
== APP == 
== APP == > test-service-2@1.0.0 start
== APP == > ts-node ./index.ts
== APP == 
== APP == 2023-04-07T15:33:28.099Z INFO [HTTPServer, HTTPServerImpl] [Topic = topic-a] Registered Subscription with routes: default
== APP == 2023-04-07T15:33:28.101Z INFO [HTTPServer, HTTPServer] Listening on 50051
== APP == 2023-04-07T15:33:28.101Z INFO [HTTPServer, HTTPServer] Registering 1 PubSub Subscriptions
== APP == 2023-04-07T15:33:28.109Z INFO [HTTPClient, HTTPClient] Sidecar Started
== APP == 2023-04-07T15:33:28.130Z INFO [HTTPServer, HTTPServer] Registered 1 PubSub Subscriptions
== APP == Received Data: "test123" with headers: {"host":"127.0.0.1:50051","user-agent":"Go-http-client/1.1","content-length":"405","content-type":"application/cloudevents+json","pubsubname":"pubsub","traceparent":"00-ccf4b7a19931f359f2227694caf6460f-4a7a5c8377b73d6f-01","accept-encoding":"gzip"}
```

Are you also running the application in a similar way with correct ports and component configuration? Can you share the command you are using?

**Comment by spethso** [comment]
@shubham1172 Thanks, the command you provided works. I was following the documentation and used the command `dapr run --app-id test-service-2 --app-port 50051 --app-protocol http -- npm run start`. The command was missing the dapr-http-port option which might be the issue.

Now, I have to find out how to run test-service-1 to publish topics. :)

**Comment by shubham1172** [comment]
Yup, otherwise a random port is assigned by the Dapr CLI. Feel free to discuss on https://aka.ms/dapr-discord if you have any confusions, or create an issue with dapr/js-sdk if you find any bugs. We can close this issue now.

**Comment by spethso** [comment]
Thanks for your help. I will try to run test-service-1 correctly and in case of problems, I will discuss it on Discord. :)
